author: Liming Wang
affiliation: UIUC
description: multilingual multimodal information bottleneck
open_source: false
train_set: Flickr Audio, LibriSpeech train-clean-100
visually_grounded: false
gpu_budget: 48
parameters:
  phonetic:
    metric: cosine
    frame_shift: 0.01
  semantic:
    metric: cosine
    pooling: mean
